nutch:
  image: apache/nutch:release-1.13
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - "mongodb:mongodb"
    - "elasticsearch:elasticsearch"
  environment:
    - SEEDLIST="http://reddit.com/r/node/"
  volumes:
    - "./config/ivy.xml:/root/nutch/ivy/ivy.xml"
    - "./config/nutch-site.template:/root/nutch/conf/nutch-site.xml"
    - "./crawldata:/root/crawldata"
mongodb:
  image: mongo
  ports:
    - "27020:27017"
  volumes:
    - "./data/mongo:/data/db"
elasticsearch:
  image: elasticsearch:1.4
  ports:
    - "9200:9200"
    - "9300:9300"